name: "DB Migration Version"
description: "Determine the database version based on the migration scripts present."
inputs:
  scriptDirectory:
    description: "Directory that contains database migration scripts"
    required: true
    default: "."
outputs:
  version:
    description: "The database version defined by the migration scripts in scriptDirectory"
runs:
  using: "node12"
  main: "dist/index.js"
